version: '3'
services:
  db-connector:
    container_name: db-connector
    restart: always
    build:
      context: ./db-connector/
      dockerfile: Dockerfile
    ports:
      - "4001:3001"
    links: 
      - mongodb
    environment:
      - DATABASE_URL=mongodb://mongodb:27017/number-validator
  mongodb:
    container_name: mongo-database
    image: mongo
    ports: 
      - "27018:27017"
    logging:
      driver: none
  number-validator: 
    container_name: number-validator
    restart: always
    build: 
      context: ./number-validator/
      dockerfile: Dockerfile
    ports:
      - "4000:3000"
    links:
      - db-connector
